### PR TITLE
Use full stops

### PR DESCRIPTION
**Pull request by TheUntraceable**
More formal

### CODE REVIEW

**Comment by WhoIsConch** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmm full stoppe

**Comment by WhoIsConch** [comment]
i m contribute
:D

**Comment by TheUntraceable** [comment]
Conch, don't drink on the job.

**Comment by WhoIsConch** [comment]
um aktually according to [this gist](https://gist.github.com/ConchDev/ba21f2b78c08ac0abb0a32c43e33779b) you get no bitches

**Comment by Lexionas74** [comment]
nah, cant be bothered

**Comment by Lexionas74** [comment]
should i demote untracable?????

**Pull request closed without merging**
