### PR TITLE
Clarify platform

### PR DESCRIPTION
**Pull request by TheUntraceable**

### CODE REVIEW

**Comment by WhoIsConch** [comment]
four big guys

**Comment by WhoIsConch** [comment]
n they bust on my eyes

**Comment by WhoIsConch** [comment]
they eat my abs jus tlike apple pie

**Comment by WhoIsConch** [comment]
if they keep seggsin me like this i might just die

**Comment by Lexionas74** [comment]
no

**Comment by TheUntraceable** [comment]
@ConchDev please refrain from spamming, I will warn you.

**Pull request closed without merging**
